[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }
size = 25

[mouse]
hide_when_typing = true

[window]
padding.x = 0
padding.y = 0
opacity = 1.0
dynamic_padding = false
decorations = "none"

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.primary]
background = "#070707"
foreground = "#f7f7f7"

[colors.normal]
black   = "#070707"
red     = "#ff5f5f"
green   = "#9a9a9a"
yellow  = "#ffaf5f"
blue    = "#79a8ff"
magenta = "#E39695"
cyan    = "#5fafff"
white   = "#f7f7f7"

[colors.bright]
black   = "#444444"
red     = "#ff5f5f"
green   = "#9a9a9a"
yellow  = "#ffaf5f"
blue    = "#79a8ff"
magenta = "#E39695"
cyan    = "#5fafff"
white   = "#ffffff"

[colors.cursor]
cursor = "#f7f7f7"
text   = "#070707"

[colors.selection]
background = "#222222"
text = "#f7f7f7"

[colors.search.matches]
background = "#303030"
foreground = "#f7f7f7"

[colors.search.focused_match]
background = "#404040"
foreground = "#ffffff"
